version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: aura_postgres
    restart: always
    environment:
      - POSTGRES_USER=aura_user
      - POSTGRES_PASSWORD=aura_password
      - POSTGRES_DB=aura_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ai_service:
    build: 
      context: ./aura-backend
      dockerfile: Dockerfile
    container_name: aura_ai_core
    command: python ai_service/main.py 
    ports:
      - "8001:8001"
    env_file:
      - ./aura-backend/.env 
    volumes:
      - ./aura-backend:/app

  backend_core:
    build: 
      context: ./aura-backend
      dockerfile: Dockerfile  
    container_name: aura_backend_api
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - ai_service
    env_file:
      - ./aura-backend/.env
    environment:
      # Ghi đè biến môi trường để đảm bảo kết nối đúng trong Docker
      - DATABASE_URL=postgresql://aura_user:aura_password@postgres_db:5432/aura_db
      - AI_SERVICE_URL=http://ai_service:8001/analyze 
    volumes:
      - ./aura-backend:/app

  frontend:
    build: ./aura-frontend
    container_name: aura_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend_core
    volumes:
      - ./aura-frontend:/app
      - /app/node_modules

volumes:
  postgres_data: