version: '3.8'

services:
  # 1. DATABASE
  mongo_db:
    image: mongo:6.0
    container_name: aura_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 2. AI SERVICE
  ai_service:
    build: 
      context: ./aura-backend
      dockerfile: Dockerfile  # <--- SỬA: Đã xóa chữ 'tools/' đi vì file giờ nằm ở ngoài
    container_name: aura_ai_core
    command: python ai_service/main.py 
    ports:
      - "8001:8001"
    env_file:
      - ./aura-backend/.env 
    volumes:
      - ./aura-backend:/app

  # 3. BACKEND CORE
  backend_core:
    build: 
      context: ./aura-backend
      dockerfile: Dockerfile  
    container_name: aura_backend_api
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
      - ai_service
    env_file:
      - ./aura-backend/.env
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/aura_db
      - AI_SERVICE_URL=http://ai_service:8001/analyze 
    volumes:
      - ./aura-backend:/app

  # 4. FRONTEND
  frontend:
    build: ./aura-frontend
    container_name: aura_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend_core
    volumes:
      - ./aura-frontend:/app
      - /app/node_modules

volumes:
  mongo_data: